// react/src/components/ui/tabs/tabs.tsx
import {
  Children,
  isValidElement,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type KeyboardEvent,
  type ReactElement,
  type ReactNode,
} from 'react';
import { LUITab, TabContext, type LUITabProps } from './tab';
import './tabs.css';

export type TabsOrientation = 'horizontal' | 'vertical';
export type TabsVariant = 'line' | 'pills';
export type TabsSize = 'sm' | 'md' | 'lg';

/** Geometry of the sliding indicator behind/under the active tab. */
interface IndicatorState {
  x: number;
  y: number;
  width: number;
  height: number;
  visible: boolean;
}

export interface LUITabsProps {
  orientation?: TabsOrientation;
  variant?: TabsVariant;
  size?: TabsSize;
  /** Stretch horizontal tabs to fill the width in equal parts. */
  grow?: boolean;
  /**
   * The active tab's `value` (or its index when no `value` was given).
   * Controlled when provided — pair with `onChange`. Omit for uncontrolled
   * use; the selection then defaults to the first enabled tab.
   */
  value?: unknown;
  /** Called with the newly active tab's value when the user selects a tab. */
  onChange?: (value: unknown) => void;
  /** Alias of `onChange` — port of the Angular `activeChange` output. */
  onActiveChange?: (value: unknown) => void;
  className?: string;
  /** `LUITab` children — the strip renders from their `label`/`icon`. */
  children?: ReactNode;
}

/**
 * Tab set with a sliding active indicator, laid out `horizontal` (default) or
 * `vertical`. Give it {@link LUITab} children — the container renders the tab
 * strip from their `label`/`icon` and shows the active tab's panel:
 *
 * ```tsx
 * <LUITabs value={tab} onChange={setTab} orientation="vertical">
 *   <LUITab label="Profile" icon="👤">…</LUITab>
 *   <LUITab label="Settings" icon="⚙️">…</LUITab>
 *   <LUITab label="Archived" disabled>…</LUITab>
 * </LUITabs>
 * ```
 *
 * Active state is the `value` prop (a tab's `value`, falling back to its
 * index) — controlled with `value` + `onChange`, or uncontrolled when `value`
 * is omitted. Follows the WAI-ARIA tabs pattern with roving arrow-key
 * navigation.
 */
export function LUITabs({
  orientation = 'horizontal',
  variant = 'line',
  size = 'md',
  grow = false,
  value: valueProp,
  onChange,
  onActiveChange,
  className,
  children,
}: LUITabsProps) {
  const baseId = useId();
  const hostRef = useRef<HTMLDivElement>(null);
  const buttonsRef = useRef<(HTMLButtonElement | null)[]>([]);

  /* The tab strip is rendered from the LUITab children's props, in order. */
  const tabs = Children.toArray(children).filter(
    (child): child is ReactElement<LUITabProps> => isValidElement(child) && child.type === LUITab,
  );

  const tabId = (index: number): string => `l-tab-${baseId}-${index}`;
  const panelId = (index: number): string => `${tabId(index)}-panel`;

  /** A tab's value, falling back to its index when none was given. */
  const valueOf = (index: number): unknown => {
    const value = tabs[index].props.value;
    return value === undefined || value === null ? index : value;
  };

  const [internalValue, setInternalValue] = useState<unknown>(null);
  const rawValue = valueProp !== undefined ? valueProp : internalValue;
  /* Default the selection to the first enabled tab (Angular did this on registration). */
  const firstEnabled = tabs.findIndex((tab) => !tab.props.disabled);
  const activeValue = rawValue ?? (firstEnabled >= 0 ? valueOf(firstEnabled) : null);

  const isActive = (index: number): boolean => valueOf(index) === activeValue;

  const select = (index: number): void => {
    const tab = tabs[index];
    if (!tab || tab.props.disabled) return;
    const value = valueOf(index);
    if (value === activeValue) return;
    setInternalValue(value);
    onChange?.(value);
    onActiveChange?.(value);
  };

  const nextEnabled = (from: number, direction: number): number => {
    const count = tabs.length;
    for (let step = 1; step <= count; step++) {
      const index = (from + direction * step + count * 2) % count;
      if (!tabs[index].props.disabled) return index;
    }
    return -1;
  };

  const onKeyDown = (event: KeyboardEvent<HTMLButtonElement>, index: number): void => {
    const vertical = orientation === 'vertical';
    let target: number;
    switch (event.key) {
      case vertical ? 'ArrowDown' : 'ArrowRight':
        target = nextEnabled(index, 1);
        break;
      case vertical ? 'ArrowUp' : 'ArrowLeft':
        target = nextEnabled(index, -1);
        break;
      case 'Home':
        target = nextEnabled(-1, 1);
        break;
      case 'End':
        target = nextEnabled(tabs.length, -1);
        break;
      default:
        return;
    }
    if (target < 0) return;
    event.preventDefault();
    select(target);
    buttonsRef.current[target]?.focus();
  };

  /* ── Sliding indicator ─────────────────────────────────────── */
  const [indicator, setIndicator] = useState<IndicatorState>({
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    visible: false,
  });
  /* Gate the slide transition until after first paint so it never flashes from 0,0. */
  const [ready, setReady] = useState(false);

  const positionIndicator = (): void => {
    const index = tabs.findIndex((_, i) => isActive(i));
    const button = buttonsRef.current[index];
    if (index < 0 || !button) {
      setIndicator((prev) => (prev.visible ? { ...prev, visible: false } : prev));
      return;
    }

    const line = variant === 'line';
    const thickness = 2;
    let geometry: { x: number; y: number; width: number; height: number };

    if (line && orientation === 'horizontal') {
      geometry = {
        x: button.offsetLeft,
        y: button.offsetTop + button.offsetHeight - thickness,
        width: button.offsetWidth,
        height: thickness,
      };
    } else if (line) {
      geometry = {
        x: button.offsetLeft + button.offsetWidth - thickness,
        y: button.offsetTop,
        width: thickness,
        height: button.offsetHeight,
      };
    } else {
      /* pills — full button rect */
      geometry = {
        x: button.offsetLeft,
        y: button.offsetTop,
        width: button.offsetWidth,
        height: button.offsetHeight,
      };
    }

    setIndicator((prev) =>
      prev.visible &&
      prev.x === geometry.x &&
      prev.y === geometry.y &&
      prev.width === geometry.width &&
      prev.height === geometry.height
        ? prev
        : { ...geometry, visible: true },
    );
  };

  /* Reposition after every commit — anything that can move the active tab or
     resize the strip (value, tabs, orientation, variant, size, grow) lands
     here; the bail-out inside positionIndicator keeps it from looping. */
  useLayoutEffect(() => {
    positionIndicator();
  });

  /* Latest closure for the ResizeObserver, which is created once on mount. */
  const positionRef = useRef(positionIndicator);
  useEffect(() => {
    positionRef.current = positionIndicator;
  });

  useEffect(() => {
    const raf = requestAnimationFrame(() => setReady(true));
    const observer = new ResizeObserver(() => positionRef.current());
    if (hostRef.current) observer.observe(hostRef.current);
    return () => {
      cancelAnimationFrame(raf);
      observer.disconnect();
    };
  }, []);

  const hostClasses = [
    'l-tabs',
    `l-tabs--${orientation}`,
    `l-tabs--${variant}`,
    `l-tabs--${size}`,
    grow ? 'l-tabs--grow' : '',
    className ?? '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div ref={hostRef} className={hostClasses}>
      <div className="l-tabs__list" role="tablist" aria-orientation={orientation}>
        {tabs.map((tab, i) => {
          const active = isActive(i);
          return (
            <button
              key={tab.key ?? i}
              ref={(el) => {
                buttonsRef.current[i] = el;
              }}
              type="button"
              role="tab"
              className={['l-tabs__tab', active ? 'is-active' : ''].filter(Boolean).join(' ')}
              id={tabId(i)}
              disabled={tab.props.disabled}
              aria-selected={active}
              aria-controls={panelId(i)}
              tabIndex={active ? 0 : -1}
              onClick={() => select(i)}
              onKeyDown={(event) => onKeyDown(event, i)}
            >
              {tab.props.icon && (
                <span className="l-tabs__icon" aria-hidden="true">
                  {tab.props.icon}
                </span>
              )}
              <span className="l-tabs__label">{tab.props.label}</span>
            </button>
          );
        })}

        <span
          className={[
            'l-tabs__indicator',
            indicator.visible ? 'is-visible' : '',
            ready ? 'is-ready' : '',
          ]
            .filter(Boolean)
            .join(' ')}
          style={{
            width: indicator.width,
            height: indicator.height,
            transform: `translate(${indicator.x}px,${indicator.y}px)`,
          }}
          aria-hidden="true"
        />
      </div>

      <div className="l-tabs__panels">
        {tabs.map((tab, i) => (
          <TabContext
            key={tab.key ?? i}
            value={{ tabId: tabId(i), panelId: panelId(i), active: isActive(i) }}
          >
            {tab}
          </TabContext>
        ))}
      </div>
    </div>
  );
}

// angular/src/app/shared/components/ui/tabs/tabs.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  afterNextRender,
  computed,
  effect,
  inject,
  input,
  model,
  output,
  signal,
  viewChildren,
} from '@angular/core';
import type { Tab } from './tab';

export type TabsOrientation = 'horizontal' | 'vertical';
export type TabsVariant = 'line' | 'pills';
export type TabsSize = 'sm' | 'md' | 'lg';

/**
 * Tab set with a sliding active indicator, laid out `horizontal` (default) or
 * `vertical`. Project {@link Tab} children — the container renders the tab strip
 * from their `label`/`icon` and shows the active tab's projected panel:
 *
 * ```html
 * <l-tabs [(value)]="tab" orientation="vertical">
 *   <l-tab label="Profile" icon="👤">…</l-tab>
 *   <l-tab label="Settings" icon="⚙️">…</l-tab>
 *   <l-tab label="Archived" [disabled]="true">…</l-tab>
 * </l-tabs>
 * ```
 *
 * Active state is a two-way `value` model (a tab's `value`, falling back to its
 * index). Follows the WAI-ARIA tabs pattern with roving arrow-key navigation.
 */
@Component({
  selector: 'l-tabs',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './tabs.html',
  styleUrl: './tabs.scss',
  host: {
    '[class]': '_hostClasses()',
  },
})
export class Tabs {
  readonly orientation = input<TabsOrientation>('horizontal');
  readonly variant = input<TabsVariant>('line');
  readonly size = input<TabsSize>('md');
  /** Stretch horizontal tabs to fill the width in equal parts. */
  readonly grow = input(false);
  /** The active tab's `value` (or its index when no `value` was given). */
  readonly value = model<unknown>(null);

  readonly activeChange = output<unknown>();

  private readonly _tabs = signal<Tab[]>([]);
  readonly tabs = this._tabs.asReadonly();

  private readonly _buttons = viewChildren<ElementRef<HTMLButtonElement>>('tabBtn');
  private readonly _host = inject<ElementRef<HTMLElement>>(ElementRef);

  /** Geometry of the sliding indicator behind/under the active tab. */
  protected readonly _indicator = signal({ x: 0, y: 0, width: 0, height: 0, visible: false });
  /** Gate the slide transition until after first paint so it never flashes from 0,0. */
  protected readonly _ready = signal(false);

  protected readonly _hostClasses = computed(() => {
    const classes = [
      'l-tabs',
      `l-tabs--${this.orientation()}`,
      `l-tabs--${this.variant()}`,
      `l-tabs--${this.size()}`,
    ];
    if (this.grow()) classes.push('l-tabs--grow');
    return classes.join(' ');
  });

  constructor() {
    const destroyRef = inject(DestroyRef);

    effect(() => {
      // Track everything that can move the active tab or resize the strip.
      this.value();
      this._tabs();
      this.orientation();
      this.variant();
      this.size();
      this.grow();
      queueMicrotask(() => this._positionIndicator());
    });

    afterNextRender(() => {
      this._positionIndicator();
      requestAnimationFrame(() => this._ready.set(true));

      const observer = new ResizeObserver(() => this._positionIndicator());
      observer.observe(this._host.nativeElement);
      destroyRef.onDestroy(() => observer.disconnect());
    });
  }

  /** @internal Called by a tab on init (in DOM order). */
  _register(tab: Tab): void {
    this._tabs.update((tabs) => [...tabs, tab]);
    // Default the selection to the first enabled tab.
    if (this.value() == null && !tab.disabled()) {
      this.value.set(this._valueOf(tab));
    }
  }

  /** @internal Called by a tab on destroy. */
  _unregister(tab: Tab): void {
    this._tabs.update((tabs) => tabs.filter((t) => t !== tab));
  }

  /** @internal A tab's value, falling back to its index when none was given. */
  _valueOf(tab: Tab): unknown {
    const value = tab.value();
    return value === undefined || value === null ? this._tabs().indexOf(tab) : value;
  }

  isActive(tab: Tab): boolean {
    return this.value() === this._valueOf(tab);
  }

  protected _select(tab: Tab): void {
    if (tab.disabled()) return;
    const value = this._valueOf(tab);
    if (value === this.value()) return;
    this.value.set(value);
    this.activeChange.emit(value);
  }

  protected _onKeydown(event: KeyboardEvent, index: number): void {
    const vertical = this.orientation() === 'vertical';
    let target = -1;
    switch (event.key) {
      case vertical ? 'ArrowDown' : 'ArrowRight':
        target = this._nextEnabled(index, 1);
        break;
      case vertical ? 'ArrowUp' : 'ArrowLeft':
        target = this._nextEnabled(index, -1);
        break;
      case 'Home':
        target = this._nextEnabled(-1, 1);
        break;
      case 'End':
        target = this._nextEnabled(this._tabs().length, -1);
        break;
      default:
        return;
    }
    if (target < 0) return;
    event.preventDefault();
    this._select(this._tabs()[target]);
    this._buttons()[target]?.nativeElement.focus();
  }

  private _nextEnabled(from: number, direction: number): number {
    const tabs = this._tabs();
    const count = tabs.length;
    for (let step = 1; step <= count; step++) {
      const index = (from + direction * step + count * 2) % count;
      if (!tabs[index].disabled()) return index;
    }
    return -1;
  }

  private _positionIndicator(): void {
    const tabs = this._tabs();
    const index = tabs.findIndex((t) => this.isActive(t));
    const button = this._buttons()[index]?.nativeElement;
    if (index < 0 || !button) {
      this._indicator.update((i) => ({ ...i, visible: false }));
      return;
    }

    const line = this.variant() === 'line';
    const thickness = 2;
    let geometry: { x: number; y: number; width: number; height: number };

    if (line && this.orientation() === 'horizontal') {
      geometry = {
        x: button.offsetLeft,
        y: button.offsetTop + button.offsetHeight - thickness,
        width: button.offsetWidth,
        height: thickness,
      };
    } else if (line) {
      geometry = {
        x: button.offsetLeft + button.offsetWidth - thickness,
        y: button.offsetTop,
        width: thickness,
        height: button.offsetHeight,
      };
    } else {
      // pills — full button rect
      geometry = {
        x: button.offsetLeft,
        y: button.offsetTop,
        width: button.offsetWidth,
        height: button.offsetHeight,
      };
    }

    this._indicator.set({ ...geometry, visible: true });
  }
}
