// react/src/components/ui/skeleton/skeleton.tsx
import type { ReactNode } from 'react';
import './skeleton.css';

export interface LUISkeletonProps {
  /** Width as any CSS length, e.g. '100%', '240px'. Ignored when `circle` is set. */
  width?: string;
  /** Height as any CSS length. Required for standalone blocks and for `circle`. */
  height?: string;
  /** Corner radius (any CSS length). Overridden to a full circle when `circle` is set. */
  radius?: string;
  /** Render a circle: width follows `height` and the radius becomes 50%. */
  circle?: boolean;
  /** Play the pulsing animation. Default: true. */
  animate?: boolean;
  /** Show the skeleton overlay (true) or reveal the wrapped content (false). */
  visible?: boolean;
  children?: ReactNode;
}

/**
 * Placeholder shown while content loads — inspired by Mantine's `Skeleton`.
 *
 * Use it standalone as a sized block (`height`/`width`/`radius`, or `circle`)
 * or wrap real content and toggle `visible`: while `visible` is true an opaque,
 * pulsing overlay covers the children; once false the content shows.
 *
 * ```tsx
 * <LUISkeleton height="1rem" width="60%" />
 * <LUISkeleton circle height="48px" />
 *
 * <LUISkeleton visible={loading}>
 *   <p>Real content, revealed when loading finishes.</p>
 * </LUISkeleton>
 * ```
 */
export function LUISkeleton({
  width = '100%',
  height,
  radius = '8px',
  circle = false,
  animate = true,
  visible = true,
  children,
}: LUISkeletonProps) {
  return (
    <div
      className="l-skeleton"
      data-visible={visible ? '' : undefined}
      data-animate={visible && animate ? '' : undefined}
      aria-hidden={visible ? true : undefined}
      style={{
        width: circle ? height : width,
        height,
        borderRadius: circle ? '50%' : radius,
      }}
    >
      {children}
    </div>
  );
}

// angular/projects/lumen-ui/src/lib/components/ui/skeleton/skeleton.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

/**
 * Placeholder shown while content loads — inspired by Mantine's `Skeleton`.
 *
 * Use it standalone as a sized block (`height`/`width`/`radius`, or `circle`)
 * or wrap real content and toggle `visible`: while `visible` is true an opaque,
 * pulsing overlay covers the projected content; once false the content shows.
 *
 * ```html
 * <l-skeleton height="1rem" width="60%" />
 * <l-skeleton [circle]="true" height="48px" />
 *
 * <l-skeleton [visible]="loading()">
 *   <p>Real content, revealed when loading finishes.</p>
 * </l-skeleton>
 * ```
 */
@Component({
  selector: 'l-skeleton',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content />',
  styleUrl: './skeleton.scss',
  host: {
    '[attr.data-visible]': 'visible() ? "" : null',
    '[attr.data-animate]': 'visible() && animate() ? "" : null',
    '[attr.aria-hidden]': 'visible() ? "true" : null',
    '[style.width]': '_width()',
    '[style.height]': 'height()',
    '[style.border-radius]': '_radius()',
  },
})
export class Skeleton {
  /** Width as any CSS length, e.g. '100%', '240px'. Ignored when `circle` is set. */
  readonly width = input<string>('100%');
  /** Height as any CSS length. Required for standalone blocks and for `circle`. */
  readonly height = input<string>();
  /** Corner radius (any CSS length). Overridden to a full circle when `circle` is set. */
  readonly radius = input<string>('8px');
  /** Render a circle: width follows `height` and the radius becomes 50%. */
  readonly circle = input(false);
  /** Play the pulsing animation. Default: true. */
  readonly animate = input(true);
  /** Show the skeleton overlay (true) or reveal the projected content (false). */
  readonly visible = input(true);

  protected readonly _width = computed(() => (this.circle() ? this.height() : this.width()));
  protected readonly _radius = computed(() => (this.circle() ? '50%' : this.radius()));
}
