// react/src/components/ui/loading-spinner/loading-spinner.tsx
import { useLUISpinner } from './spinner-provider';
import './loading-spinner.css';

/**
 * Full-screen loading overlay driven by `useLUISpinner()`. Place one instance
 * near the app root (inside `LUISpinnerProvider`); call `show()` / `hide()`
 * from anywhere to toggle it.
 *
 * ```tsx
 * <LUILoadingSpinner />
 * ```
 */
export function LUILoadingSpinner() {
  const spinner = useLUISpinner();

  if (!spinner.visible) return null;

  return (
    <div className="l-spinner-overlay">
      <div className="l-spinner-wheel"></div>
    </div>
  );
}

// angular/src/app/shared/components/ui/loading-spinner/loading-spinner.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { SpinnerService } from '../../../services/spinner.service';

/**
 * Full-screen loading overlay driven by {@link SpinnerService}. Place one
 * instance near the app root; call `SpinnerService.show()` / `hide()` from
 * anywhere to toggle it.
 *
 * ```html
 * <l-loading-spinner />
 * ```
 */
@Component({
  selector: 'l-loading-spinner',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [],
  templateUrl: './loading-spinner.html',
  styleUrl: './loading-spinner.scss',
})
export class LoadingSpinner {
  private readonly _spinner = inject(SpinnerService);
  protected readonly _visible = this._spinner.visible;
}
