// angular/projects/lumen-ui/src/lib/components/ui/tabs/tab.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnDestroy,
  OnInit,
  computed,
  inject,
  input,
} from '@angular/core';
import { Tabs } from './tabs';

let _uid = 0;

/**
 * A single tab inside {@link Tabs}. Carries the strip label (`label`/`icon`) and
 * projects its panel content via `<ng-content>`. The parent tab set owns the
 * active state; this component only shows or hides its panel accordingly.
 */
@Component({
  selector: 'l-tab',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './tab.html',
  styleUrl: './tab.scss',
})
export class Tab implements OnInit, OnDestroy {
  /** Strip label. */
  readonly label = input<string>('');
  /** Optional leading glyph/emoji. */
  readonly icon = input<string>('');
  /** Explicit value bound to `l-tabs` `value`. Defaults to the tab's index. */
  readonly value = input<unknown>();
  readonly disabled = input(false);

  readonly tabId = `l-tab-${_uid++}`;
  readonly panelId = `${this.tabId}-panel`;

  private readonly _tabs = inject(Tabs);

  protected readonly _active = computed(() => this._tabs.isActive(this));

  ngOnInit(): void {
    this._tabs._register(this);
  }

  ngOnDestroy(): void {
    this._tabs._unregister(this);
  }
}

// react/src/components/ui/tabs/tab.tsx
import { createContext, use, type ReactNode } from 'react';
import './tab.css';

/** @internal Ids and active state assigned to a tab by its parent {@link LUITabs}. */
export interface TabContextValue {
  tabId: string;
  panelId: string;
  active: boolean;
}

export const TabContext = createContext<TabContextValue | null>(null);

export interface LUITabProps {
  /** Strip label. */
  label?: string;
  /** Optional leading glyph/emoji. */
  icon?: string;
  /** Explicit value bound to `LUITabs` `value`. Defaults to the tab's index. */
  value?: unknown;
  /** Disable the tab; it is skipped by arrow-key navigation. */
  disabled?: boolean;
  /** Panel content, shown while the tab is active. */
  children?: ReactNode;
}

/**
 * A single tab inside {@link LUITabs}. Carries the strip label (`label`/`icon`)
 * and renders its panel content (`children`). The parent tab set owns the
 * active state and reads `label`/`icon`/`value`/`disabled` straight off this
 * element — `LUITab` must be a direct child of `LUITabs`.
 */
export function LUITab({ children }: LUITabProps) {
  const tab = use(TabContext);
  if (!tab) {
    throw new Error('LUITab must be rendered inside LUITabs');
  }

  return (
    <div className="l-tab">
      <div
        className={['l-tab__panel', tab.active ? 'is-active' : ''].filter(Boolean).join(' ')}
        role="tabpanel"
        id={tab.panelId}
        aria-labelledby={tab.tabId}
        hidden={!tab.active}
        inert={!tab.active}
      >
        {children}
      </div>
    </div>
  );
}
