// react/src/components/ui/drawer/drawer-container.tsx
import { useEffect, useState, type CSSProperties, type ReactNode } from 'react';
import type { DrawerRef } from './drawer-ref';
import './drawer-container.css';

type DrawerState = 'enter' | 'leave';

export interface DrawerContainerProps {
  drawerRef: DrawerRef;
  children?: ReactNode;
}

/**
 * Host component rendered into `<body>` (via `createPortal`) by
 * `LUIDrawerProvider`. Owns the backdrop, the edge-anchored panel, the
 * position-driven slide animations, and renders the supplied content.
 */
export function DrawerContainer({ drawerRef, children }: DrawerContainerProps) {
  const [state, setState] = useState<DrawerState>('enter');
  const config = drawerRef.config;

  useEffect(() => {
    // Let the container drive the leave animation when close() is called.
    drawerRef._setStartClose(() => setState('leave'));
  }, [drawerRef]);

  useEffect(() => {
    const onKeydown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !drawerRef.config.disableClose) {
        drawerRef.close();
      }
    };
    document.addEventListener('keydown', onKeydown);
    return () => document.removeEventListener('keydown', onKeydown);
  }, [drawerRef]);

  const onBackdropClick = () => {
    if (!drawerRef.config.disableClose) {
      drawerRef.close();
    }
  };

  const position = config.position ?? 'right';
  const isHorizontal = position === 'left' || position === 'right';
  const extra = config.panelClass
    ? Array.isArray(config.panelClass)
      ? config.panelClass
      : [config.panelClass]
    : [];
  const panelClasses = [
    'drawer-panel',
    `drawer-panel--${position}`,
    `drawer-anim--${state}`,
    ...extra,
  ].join(' ');

  return (
    <div
      className={state === 'leave' ? 'drawer-overlay drawer-overlay--leaving' : 'drawer-overlay'}
      style={{ '--drawer-duration': `${config.animationDuration ?? 280}ms` } as CSSProperties}
    >
      {config.backdrop !== false && <div className="drawer-backdrop" onClick={onBackdropClick} />}

      <div
        className={panelClasses}
        style={{
          width: isHorizontal ? config.size : undefined,
          height: !isHorizontal ? config.size : undefined,
        }}
        role="dialog"
        aria-modal="true"
        onAnimationEnd={(event) => {
          // Only react to the panel's own animation, and only on the way out.
          if (event.target === event.currentTarget && state === 'leave') {
            drawerRef._finishClose();
          }
        }}
      >
        {children}
      </div>
    </div>
  );
}

// angular/src/app/shared/components/ui/drawer/drawer-container.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  Injector,
  TemplateRef,
  Type,
  ViewContainerRef,
  computed,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import { DrawerRef } from './drawer-ref';
import { DRAWER_DATA, DrawerConfig } from './drawer.config';

type DrawerState = 'enter' | 'leave';

/**
 * Host component rendered into `<body>` by {@link DrawerService}. Owns the
 * backdrop, the edge-anchored panel, the position-driven slide animations,
 * and renders the supplied content — either a `TemplateRef` or a Component type.
 */
@Component({
  selector: 'l-drawer-container',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [],
  template: `
    <div
      class="drawer-overlay"
      [class.drawer-overlay--leaving]="_state() === 'leave'"
      [style.--drawer-duration.ms]="config.animationDuration"
    >
      @if (config.backdrop !== false) {
        <div class="drawer-backdrop" (click)="_onBackdropClick()"></div>
      }

      <div
        class="drawer-panel"
        [class]="_panelClasses()"
        [style.width]="_isHorizontal() ? config.size : null"
        [style.height]="!_isHorizontal() ? config.size : null"
        role="dialog"
        aria-modal="true"
        (animationend)="_onAnimationEnd($event)"
      >
        <ng-container #content />
      </div>
    </div>
  `,
  styleUrl: './drawer-container.scss',
  host: {
    '(document:keydown.escape)': '_onEscape()',
  },
})
export class DrawerContainer implements AfterViewInit {
  /** Content to project — a `TemplateRef` or a Component class. Assigned by DrawerService. */
  content!: TemplateRef<unknown> | Type<unknown>;
  config!: DrawerConfig;
  drawerRef!: DrawerRef;
  /** Injector of the caller, used as the parent for component content. */
  parentInjector!: Injector;

  protected readonly _state = signal<DrawerState>('enter');

  private readonly _contentAnchor = viewChild.required('content', { read: ViewContainerRef });
  private readonly _cdr = inject(ChangeDetectorRef);

  protected readonly _isHorizontal = computed(() => {
    const pos = this.config.position ?? 'right';
    return pos === 'left' || pos === 'right';
  });

  protected readonly _panelClasses = computed(() => {
    const pos = this.config.position ?? 'right';
    const classes = ['drawer-panel', `drawer-panel--${pos}`, `drawer-anim--${this._state()}`];
    const extra = this.config.panelClass;
    if (extra) {
      classes.push(...(Array.isArray(extra) ? extra : [extra]));
    }
    return classes.join(' ');
  });

  ngAfterViewInit(): void {
    // Let the container drive the leave animation when close() is called.
    this.drawerRef._startClose = () => this._startLeave();
    this._renderContent();
    this._cdr.detectChanges();
  }

  protected _onAnimationEnd(event: AnimationEvent): void {
    // Only react to the panel's own animation, and only on the way out.
    if (event.target === event.currentTarget && this._state() === 'leave') {
      this.drawerRef._finishClose();
    }
  }

  protected _onBackdropClick(): void {
    if (!this.config.disableClose) {
      this.drawerRef.close();
    }
  }

  protected _onEscape(): void {
    if (!this.config.disableClose) {
      this.drawerRef.close();
    }
  }

  private _renderContent(): void {
    const anchor = this._contentAnchor();
    if (this.content instanceof TemplateRef) {
      anchor.createEmbeddedView(this.content, {
        $implicit: this.config.data,
        data: this.config.data,
        drawerRef: this.drawerRef,
      });
    } else {
      const injector = Injector.create({
        parent: this.parentInjector,
        providers: [
          { provide: DrawerRef, useValue: this.drawerRef },
          { provide: DRAWER_DATA, useValue: this.config.data ?? null },
        ],
      });
      const ref = anchor.createComponent(this.content, { injector });
      this.drawerRef.componentInstance = ref.instance;
    }
  }

  private _startLeave(): void {
    if (this._state() === 'leave') {
      return;
    }
    this._state.set('leave');
    this._cdr.detectChanges();
  }
}
