// angular/src/app/shared/components/ui/card/card.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  input,
} from '@angular/core';

export type CardVariant = 'default' | 'dark';
export type CardPadding = 'none' | 'sm' | 'md' | 'lg';
export type CardShadow = 'none' | 'sm' | 'md' | 'lg';

/**
 * A surface container for grouping related content — the shared page-section
 * style as a component. Optional header (`title` input, left) with a
 * `[card-extra]` slot on its right, a `[card-footer]` slot below a divider,
 * and `padding`, `shadow`, `bordered` and `hoverable` presentation inputs.
 *
 * ```html
 * <l-card title="Project settings" shadow="sm">
 *   <l-button card-extra variant="ghost" size="sm">Edit</l-button>
 *   Body content.
 *   <span card-footer>Updated 2 days ago</span>
 * </l-card>
 * ```
 */
@Component({
  selector: 'l-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './card.html',
  styleUrl: './card.scss',
  // Unscoped on purpose: the header/footer collapse when nothing is projected
  // into them, which needs :empty/:has against the projected content — that
  // content belongs to the consumer's scope, so emulated encapsulation can't
  // reach it. Class names are component-prefixed to stay collision-free.
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': '_hostClasses()',
  },
})
export class Card {
  /** Surface tint — `dark` uses the darker section background. */
  readonly variant = input<CardVariant>('default');

  /** Inner padding of each region: `none` 0, `sm` 8, `md` 12, `lg` 20 (px). */
  readonly padding = input<CardPadding>('md');

  /** Drop-shadow strength. */
  readonly shadow = input<CardShadow>('none');

  /** Show the 1px border around the card. */
  readonly bordered = input(true);

  /** Lift the card and add a shadow on hover — for clickable cards. */
  readonly hoverable = input(false);

  /** Header title, rendered on the left. Adding it (or `[card-extra]` content) shows the header. */
  readonly title = input('');

  protected readonly _hostClasses = computed(() =>
    [
      'lui-card',
      this.variant() === 'dark' ? 'lui-card-dark' : '',
      `lui-card-pad-${this.padding()}`,
      this.shadow() !== 'none' ? `lui-card-shadow-${this.shadow()}` : '',
      this.bordered() ? '' : 'lui-card-borderless',
      this.hoverable() ? 'lui-card-hoverable' : '',
    ]
      .filter(Boolean)
      .join(' '),
  );
}

// react/src/components/ui/card/card.tsx
import type { ComponentPropsWithRef, ReactNode } from 'react';
import './card.css';

export type CardVariant = 'default' | 'dark';
export type CardPadding = 'none' | 'sm' | 'md' | 'lg';
export type CardShadow = 'none' | 'sm' | 'md' | 'lg';

export interface LUICardProps extends Omit<ComponentPropsWithRef<'div'>, 'title'> {
  /** Surface tint — `dark` uses the darker section background. */
  variant?: CardVariant;

  /** Inner padding of each region: `none` 0, `sm` 8, `md` 12, `lg` 20 (px). */
  padding?: CardPadding;

  /** Drop-shadow strength. */
  shadow?: CardShadow;

  /** Show the 1px border around the card. */
  bordered?: boolean;

  /** Lift the card and add a shadow on hover — for clickable cards. */
  hoverable?: boolean;

  /** Header title, rendered on the left. Adding it (or `extra`) shows the header. */
  title?: ReactNode;

  /** Header content rendered on the right (actions, links). */
  extra?: ReactNode;

  /** Footer content, separated from the body by a divider. */
  footer?: ReactNode;
}

export function LUICard({
  variant = 'default',
  padding = 'md',
  shadow = 'none',
  bordered = true,
  hoverable = false,
  title,
  extra,
  footer,
  className,
  children,
  ...rest
}: LUICardProps) {
  const hasHeader = title != null || extra != null;

  const classes = [
    'lui-card',
    variant === 'dark' ? 'lui-card-dark' : '',
    `lui-card-pad-${padding}`,
    shadow !== 'none' ? `lui-card-shadow-${shadow}` : '',
    bordered ? '' : 'lui-card-borderless',
    hoverable ? 'lui-card-hoverable' : '',
    className ?? '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes} {...rest}>
      {hasHeader && (
        <div className="lui-card__header">
          {title != null && <div className="lui-card__title">{title}</div>}
          {extra != null && <div className="lui-card__extra">{extra}</div>}
        </div>
      )}
      <div className="lui-card__body">{children}</div>
      {footer != null && <div className="lui-card__footer">{footer}</div>}
    </div>
  );
}
